version: '3'
services:
  dnsmasq:
    image: jpillora/dnsmasq
    ports:
      - 53535:53/tcp
      - 53535:53/udp
      - 5380:8080
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      - USER=mmd
      - PASS=123123
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
      - 9443:9443
      - 8286:8286
    restart: always